### ISSUE TITLE
nedetekuje se jako validni adresa

### ISSUE THREAD

**Issue by michalbcz** [krtek/reality#1]
http://www.bezrealitky.cz/nemovitosti-byty-domy/427741-nabidka-prodej-bytu-winklerova-praha

**Comment by bedla** [comment]
v logu vidim:

Real Reality contentscript loaded
Real Reality: page load event called
Real Reality: address parsed:  Winklerova, Praha - Dubeč

a vyhledavani pres google formular vrati toto https://goo.gl/maps/87kKaJT7k3U2

co presne znamena "nevalidni adresa"?

**Comment by michalbcz** [comment]
hmm uz to funguje, kdyz jsem to zkousel tak google geocoding api vracelo "ZERO_RESULTS"
